### ISSUE TITLE
Inscription uhdbits

### ISSUE THREAD

**Issue by bubuleur** [rik91/script.quasar.uhdbits-rik91#1]
Bonjour,
Je vous embête encore mais juste pour savoir je pense que c'est pas le bon endroit pour ca mais comment s’inscrire sur le site uhdbits impossible de trouver quelqu chose sur gogole a moins que j'ai pas trouver le bon endroit, poutant j'ai fouillé
Si cela vous dérange pas biensur
Cordialement
Merci

**Comment by rik91** [comment]
Déjà pour commencer, j'avais codé ce provider pour quelqu'un qui me l'avais demandé, mais je ne crois pas qu'il fonctionne encore.
De plus ce n'est pas un provider avec des torrent français comme cpasbien ou t411 si c'est ce que vous cherchez...
Concernant l'inscription, il me semble qu'il y a des périodes ou ils ouvrent les inscriptions, mais pas tout le temps. Sinon il doit y avoir un système d'invitation pour ceux qui ont un compte et qui veulent invité des gens.

**Comment by bubuleur** [comment]
Ah ok d'accord merci de m'avoir éclairé c'est vrai que je recherche surtout des providers français 
Ps: Ça a l'air compliquer pour s'inscrire sur uhdbits
Sinon vous en connaissais d'autre providers français ou il pourrait y avoir des films français?
J’utilisai celui pour kickass.to mais vu que le site a fermé
Sinon a tout hasard j'ai trouvé un site récemment c'est 
http://www.torrent9.biz 
cela serait possible de faire un provider sur ce site si c'est possible biensur
Je me demande mais je sais pas si ce site fait pas parti de cpasbien
Merci encore pour votre rapidité pour répondre et encore pour vos providers
Sinon dernière petite question j'ai trouvé un provider pour le site idope.se qui a l'ai pas mal pour les films fr 
mais j'arrive pas a le faire fonctionner avec quasar
Cordialement

**Comment by rik91** [comment]
Concernant uhdbits, je pense que vous pouvez laissé tomber.

En gros j'avais fait les 2 seuls gros providers français car yen avait pas d'autre à l'époque.
Je pense qu'avec ces 2 là, on trouve quasi tout ce qu'on veut avec pas mal de choix en qualité.

Pour torrent9.biz, j'ai l'impression en effet que c'est une copie de cpasbien. j'ai fait quelques recherches sur les 2 sites et ça renvoi à chaque fois le même nombre de résultat et quand on y regarde le plus près, c'est exactement les mêmes résultats. 
Je pense donc que c'est les mêmes torrents derrière donc ça a peu d’intérêt de recréer un provider si c'est pour avoir les résultats en double.

Pour idope.se, donnez moi le lien du provider, je peux jeter un oeil...

Rik91

**Comment by bubuleur** [comment]
Ok dac pour uhdbits si il y a pas de films français dessus c'est pas la peine
Pour torrent9 c'est bien ce que j'avais cru voir ça sert a rien oui de faire un provider pour ça
Sinon pour idope :
https://offshoregit.com/pulsarunofficial/Unofficial-Quasar-Repo/script.magnetic.idope-mc/script.magnetic.idope-mc-0.7.7.zip
Merci

**Comment by rik91** [comment]
Concernant le provider idope, c'est un provider codé par mancuniancol.
Pour pouvoir utiliser ses providers il faut installer une autre extension avant, le module magnetic.
Si vous allez sur son github : https://github.com/mancuniancol/script.magnetic.idope-mc il y a un lien en bas qui vous renvoi vers une page vous expliquant comment installer ce qu'il faut pour le faire fonctionner.
=> https://github.com/mancuniancol/repository.magnetic

**Comment by bubuleur** [comment]
Ah d'accord merci pour l'aide je fouillé hier soir et je suis tomber sur ce site
http://ftp.acc.umu.se/mirror/addons.superrepo.org/v7/addons/
il y a pas mal de providers je vais les essayer pour voir

**Comment by rik91** [comment]
Pour info j'ai codé un provider pour http://www.torrent9.biz
Il n'y a plus de nouveau contenu publié sur cpasbien, torrent9 contient tous les torrents de cpasbien + les nouveaux ajouts
